version: '3.8'

services:
  my5gcore-upf-1:
    container_name: upf1
    build:
      context: ./nf_upf
      args:
        DEBUG_TOOLS: "false"
    command: ./free5gc-upfd -f ../config-v3.0.3/upfcfg.yaml
    volumes:
      - "./config-v3.0.3/upfcfg1.yaml:/my5Gcore/config-v3.0.3/upfcfg.yaml"
    cap_add:
      - NET_ADMIN
    networks:
      5gcorenetwork:
        aliases:
          - upf1.my5Gcore.org
  db:
    container_name: mongodb
    image: mongo
    #command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - dbdata:/data/db
    networks:
      5gcorenetwork:
        aliases:
          - db

  my5gcore-nrf:
    container_name: nrf
    build:
      context: ./nf_nrf
      args:
        DEBUG_TOOLS: "false"
    command: ./nrf -nrfcfg ../config-v3.0.3/nrfcfg.conf
    expose:
      - "29510"
    volumes:
      - ./config-v3.0.3/nrfcfg.conf:/my5Gcore/config-v3.0.3/nrfcfg.conf
      - ./config-v3.0.3/my5Gcore.conf:/my5Gcore/config-v3.0.3/my5Gcore.conf
    environment:
      DB_URI: mongodb://db/my5Gcore
      GIN_MODE: release
    networks:
      5gcorenetwork:
        aliases:
          - nrf.my5Gcore.org
    depends_on:
      - db

  my5gcore-amf:
    container_name: amf
    build:
      context: ./nf_amf
      args:
        DEBUG_TOOLS: "false"
    command: ./amf -amfcfg ../config-v3.0.3/amfcfg.conf
    expose:
      - "29518"
    volumes:
      - ./config-v3.0.3/amfcfg.conf:/my5Gcore/config-v3.0.3/amfcfg.conf
      - ./config-v3.0.3/my5Gcore.conf:/my5Gcore/config-v3.0.3/my5Gcore.conf
    environment:
      GIN_MODE: release
    networks:
      5gcorenetwork:
        aliases:
          - amf.my5Gcore.org
    depends_on:
      - my5gcore-nrf

  my5gcore-ausf:
    container_name: ausf
    build:
      context: ./nf_ausf
      args:
        DEBUG_TOOLS: "false"
    command: ./ausf -ausfcfg ../config-v3.0.3/ausfcfg.conf
    expose:
      - "29509"
    volumes:
      - ./config-v3.0.3/ausfcfg.conf:/my5Gcore/config-v3.0.3/ausfcfg.conf
      - ./config-v3.0.3/my5Gcore.conf:/my5Gcore/config-v3.0.3/my5Gcore.conf
    environment:
      GIN_MODE: release
    networks:
      5gcorenetwork:
        aliases:
          - ausf.my5Gcore.org
    depends_on:
      - my5gcore-nrf

  my5gcore-nssf:
    container_name: nssf
    build:
      context: ./nf_nssf
      args:
        DEBUG_TOOLS: "false"
    command: ./nssf -nssfcfg ../config-v3.0.3/nssfcfg.conf
    expose:
      - "29531"
    volumes:
      - ./config-v3.0.3/nssfcfg.conf:/my5Gcore/config-v3.0.3/nssfcfg.conf
      - ./config-v3.0.3/my5Gcore.conf:/my5Gcore/config-v3.0.3/my5Gcore.conf
    environment:
      GIN_MODE: release
    networks:
      5gcorenetwork:
        aliases:
          - nssf.my5Gcore.org
    depends_on:
      - my5gcore-nrf

  my5gcore-pcf:
    container_name: pcf
    build:
      context: ./nf_pcf
      args:
        DEBUG_TOOLS: "false"
    command: ./pcf -pcfcfg ../config-v3.0.3/pcfcfg.conf
    expose:
      - "29507"
    volumes:
      - ./config-v3.0.3/pcfcfg.conf:/my5Gcore/config-v3.0.3/pcfcfg.conf
      - ./config-v3.0.3/my5Gcore.conf:/my5Gcore/config-v3.0.3/my5Gcore.conf
    environment:
      GIN_MODE: release
    networks:
      5gcorenetwork:
        aliases:
          - pcf.my5Gcore.org
    depends_on:
      - my5gcore-nrf

  my5gcore-smf:
    container_name: smf
    build:
      context: ./nf_smf
      args:
        DEBUG_TOOLS: "false"
    command: ./smf -smfcfg ../config-v3.0.3/smfcfg.conf -uerouting ../config-v3.0.3/uerouting.yaml
    expose:
      - "29502"
    volumes:
      - ./config-v3.0.3/smfcfg.conf:/my5Gcore/config-v3.0.3/smfcfg.conf
      - ./config-v3.0.3/uerouting.yaml:/my5Gcore/config-v3.0.3/uerouting.yaml
      - ./config-v3.0.3/my5Gcore.conf:/my5Gcore/config-v3.0.3/free5gc.conf
    environment:
      GIN_MODE: release
    networks:
      5gcorenetwork:
        ipv4_address: 10.100.200.100
        aliases:
          - smf.my5Gcore.org
    depends_on:
      - my5gcore-nrf

  my5gcore-udm:
    container_name: udm
    build:
      context: ./nf_udm
      args:
        DEBUG_TOOLS: "false"
    command: ./udm -udmcfg ../config-v3.0.3/udmcfg.conf
    expose:
      - "29503"
    volumes:
      - ./config-v3.0.3/udmcfg.conf:/my5Gcore/config-v3.0.3/udmcfg.conf
      - ./config-v3.0.3/my5Gcore.conf:/my5Gcore/config-v3.0.3/my5Gcore.conf
    environment:
      GIN_MODE: release
    networks:
      5gcorenetwork:
        aliases:
          - udm.my5Gcore.org
    depends_on:
      - db
      - my5gcore-nrf

  my5gcore-udr:
    container_name: udr
    build:
      context: ./nf_udr
      args:
        DEBUG_TOOLS: "false"
    command: ./udr -udrcfg ../config-v3.0.3/udrcfg.conf
    expose:
      - "29504"
    environment:
      GIN_MODE: release
    volumes:
      - ./config-v3.0.3/udrcfg.conf:/my5Gcore/config-v3.0.3/udrcfg.conf
      - ./config-v3.0.3/my5Gcore.conf:/my5Gcore/config-v3.0.3/my5Gcore.conf
    environment:
      DB_URI: mongodb://db/my5Gcore
      GIN_MODE: release
    networks:
      5gcorenetwork:
        aliases:
          - udr.my5Gcore.org
    depends_on:
      - db
      - my5gcore-nrf

  my5gcore-n3iwf:
    container_name: n3iwf
    build:
      context: ./nf_n3iwf
      args:
        DEBUG_TOOLS: "false"
    command: sh -c "./n3iwf-ipsec.sh && ./n3iwf -n3iwfcfg ../config-v3.0.3/n3iwfcfg.conf"
    volumes:
      - ./config-v3.0.3/n3iwfcfg.conf:/my5Gcore/config-v3.0.3/n3iwfcfg.conf
      - ./config-v3.0.3/my5Gcore.conf:/my5Gcore/config-v3.0.3/free5gc.conf
      - ./config-v3.0.3/n3iwf-ipsec.sh:/my5Gcore/n3iwf/n3iwf-ipsec.sh
    environment:
      GIN_MODE: release
    cap_add:
      - NET_ADMIN
    networks:
      5gcorenetwork:
        aliases:
          - n3iwf.my5Gcore.org

  my5gcore-webui:
    container_name: webui
    build:
      context: ./webui
      args:
        DEBUG_TOOLS: "false"
    command: ./webui -free5gccfg ../config/free5gc.conf --webuicfg ../config/webuicfg.conf
    volumes:
      - ./config-v3.0.3/webuicfg.conf:/my5Gcore/config/webuicfg.conf
      - ./config-v3.0.3/my5Gcore.conf:/my5Gcore/config/free5gc.conf
    environment:
      - GIN_MODE=release
    networks:
      5gcorenetwork:
        aliases:
          - webui
    ports:
      - "5000:5000"
    depends_on:
      - db

networks:
  5gcorenetwork:
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.0/24

volumes:
  dbdata:
