version: '2.1'

services:
  free5gc-upf:
    container_name: upf
    build:
      context: ./nf_upf
      args:
        DEBUG_TOOLS: "false"
    command: ./free5gc-upfd -f ../config/upfcfg.yaml
    volumes:
      - "./config/upfcfg.yaml:/free5gc/config/upfcfg.yaml"
    cap_add:
      - NET_ADMIN
    networks:
      N3:
        ipv4_address: 10.200.200.102
      N4:
        ipv4_address: 10.200.250.101
#      N6:
#        ipv4_address: 60.60.0.101

  db:
    container_name: mongodb
    image: mongo
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - dbdata:/data/db
    networks:
      5GC:
        ipv4_address: 10.1.1.11
        aliases:
          - db

  free5gc-nrf:
    container_name: nrf
    build:
      context: ./nf_nrf
      args:
        DEBUG_TOOLS: "false"
    command: ./nrf -nrfcfg ../config/nrfcfg.conf
    expose:
      - "29510"
    volumes:
      - ./config/nrfcfg.conf:/free5gc/config/nrfcfg.conf
      - ./config/free5GC.conf:/free5gc/config/free5GC.conf
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      5GC:
        ipv4_address: 10.1.1.10
        aliases:
          - nrf
    depends_on:
      - db

  free5gc-amf:
    container_name: amf
    build:
      context: ./nf_amf
      args:
        DEBUG_TOOLS: "false"
    command: ./amf -amfcfg ../config/amfcfg.conf
    expose:
      - "29518"
    volumes:
      - ./config/amfcfg.conf:/free5gc/config/amfcfg.conf
      - ./config/free5GC.conf:/free5gc/config/free5GC.conf
    environment:
      GIN_MODE: release
    networks:
      N2:
        ipv4_address: 172.16.0.1
      5GC:
        ipv4_address: 10.1.1.2
        aliases:
          - amf
    depends_on:
      - free5gc-nrf

  free5gc-ausf:
    container_name: ausf
    build:
      context: ./nf_ausf
      args:
        DEBUG_TOOLS: "false"
    command: ./ausf -ausfcfg ../config/ausfcfg.conf
    expose:
      - "29509"
    volumes:
      - ./config/ausfcfg.conf:/free5gc/config/ausfcfg.conf
      - ./config/free5GC.conf:/free5gc/config/free5GC.conf
    environment:
      GIN_MODE: release
    networks:
      5GC:
        ipv4_address: 10.1.1.4
        aliases:
          - ausf
    depends_on:
      - free5gc-nrf

  free5gc-nssf:
    container_name: nssf
    build:
      context: ./nf_nssf
      args:
        DEBUG_TOOLS: "false"
    command: ./nssf -nssfcfg ../config/nssfcfg.conf
    expose:
      - "29531"
    volumes:
      - ./config/nssfcfg.conf:/free5gc/config/nssfcfg.conf
      - ./config/free5GC.conf:/free5gc/config/free5GC.conf
    environment:
      GIN_MODE: release
    networks:
      5GC:
        ipv4_address: 10.1.1.5
        aliases:
          - nssf
    depends_on:
      - free5gc-nrf

  free5gc-pcf:
    container_name: pcf
    build:
      context: ./nf_pcf
      args:
        DEBUG_TOOLS: "false"
    command: ./pcf -pcfcfg ../config/pcfcfg.conf
    expose:
      - "29507"
    volumes:
      - ./config/pcfcfg.conf:/free5gc/config/pcfcfg.conf
      - ./config/free5GC.conf:/free5gc/config/free5GC.conf
    environment:
      GIN_MODE: release
    networks:
      5GC:
        ipv4_address: 10.1.1.6
        aliases:
          - pcf
    depends_on:
      - free5gc-nrf

  free5gc-smf:
    container_name: smf
    build:
      context: ./nf_smf
      args:
        DEBUG_TOOLS: "false"
    command: ./smf -smfcfg ../config/smfcfg.conf -uerouting ../config/uerouting.yaml
    expose:
      - "29502"
    volumes:
      - ./config/smfcfg.conf:/free5gc/config/smfcfg.conf
      - ./config/uerouting.yaml:/free5gc/config/uerouting.yaml
      - ./config/free5GC.conf:/free5gc/config/free5GC.conf
    environment:
      GIN_MODE: release
    networks:
      5GC:
        ipv4_address: 10.1.1.3
        aliases:
          - smf
      N4:
        ipv4_address: 10.200.250.1
        aliases:
          - smf
    depends_on:
      - free5gc-nrf
      - free5gc-upf

  free5gc-udm:
    container_name: udm
    build:
      context: ./nf_udm
      args:
        DEBUG_TOOLS: "false"
    command: ./udm -udmcfg ../config/udmcfg.conf
    expose:
      - "29503"
    volumes:
      - ./config/udmcfg.conf:/free5gc/config/udmcfg.conf
      - ./config/free5GC.conf:/free5gc/config/free5GC.conf
    environment:
      GIN_MODE: release
    networks:
      5GC:
#        link_local_ips:
#          - 10.1.1.7
        ipv4_address: 10.1.1.7
        aliases:
          - udm
    depends_on:
      - db
      - free5gc-nrf

  free5gc-udr:
    container_name: udr
    build:
      context: ./nf_udr
      args:
        DEBUG_TOOLS: "false"
    command: ./udr -udrcfg ../config/udrcfg.conf
    expose:
      - "29504"
    volumes:
      - ./config/udrcfg.conf:/free5gc/config/udrcfg.conf
      - ./config/free5GC.conf:/free5gc/config/free5GC.conf
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      5GC:
        ipv4_address: 10.1.1.8
        aliases:
          - udr
    depends_on:
      - db
      - free5gc-nrf

  free5gc-n3iwf:
    container_name: n3iwf
    build:
      context: ./nf_n3iwf
      args:
        DEBUG_TOOLS: "false"
    command: ./n3iwf-ipsec.sh
    volumes:
      - ./config/n3iwfcfg.conf:/free5gc/config/n3iwfcfg.conf
      - ./config/free5GC.conf:/free5gc/config/free5GC.conf
      - ./config/n3iwf-ipsec.sh:/free5gc/n3iwf/n3iwf-ipsec.sh
    environment:
      GIN_MODE: release
    cap_add:
      - NET_ADMIN
    networks:
      NWu:
        ipv4_address: 192.168.127.1
        aliases:
          - n3iwf
      N2:
        ipv4_address: 172.16.0.2
      N3:
        ipv4_address: 10.200.200.2
        aliases:
          - n3iwf
    depends_on:
      - free5gc-amf
      - free5gc-smf
      - free5gc-upf

  free5gc-webui:
    container_name: webui
    build:
      context: ./webui
      args:
        DEBUG_TOOLS: "false"
    command: ./webui
    volumes:
      - ./config/webuicfg.conf:/free5gc/config/webuicfg.conf
      - ./config/free5GC.conf:/free5gc/config/free5GC.conf
    environment:
      - GIN_MODE=release
    networks:
      5GC:
        ipv4_address: 10.1.1.20
        aliases:
          - webui
    ports:
      - "5000:5000"
    depends_on:
      - db

#  internet:
#    container_name: internet
#    build:
#      context: internet
#    networks:
#      N6:
#        ipv4_address: 60.60.0.102
#        aliases:
#          - internet
#    ports:
#      - "80:80"

  n3ue:
    container_name: n3ue
    build:
      context: ../
      dockerfile: Dockerfile_n3ue
    command: ./ue-ipsec.sh
    volumes:
      - ./config/uecfg.conf:/go/src/free5gc/config/uecfg.conf
      - ./config/free5GC.conf:/go/src/free5gc/config/free5GC.conf
      - ./config/ue-ipsec.sh:/go/src/free5gc/bin/ue-ipsec.sh
    cap_add:
      - NET_ADMIN
    networks:
      NWu:
        ipv4_address: 192.168.127.2
        aliases:
          - n3ue
    ports:
      - "10000:10000"
    depends_on:
      - free5gc-n3iwf

networks:
  5GC:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.254

  NWu:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.127.0/24
          gateway: 192.168.127.254

  N2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.254

  N3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.200.0/24
          gateway: 10.200.200.254

  N4:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.250.0/24
          gateway: 10.200.250.254

#  N6:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 60.60.100.0/24

volumes:
  dbdata:
